const MAX_MINUTES_WAITING_TO_PAY = 10;
const MAX_DAYS_WAITING_FOR_SHOP_CONFIRMATION = 1;
const ORDER_MOMO_TRANSACTION_EXPIRY_TIME_IN_MINUTE = MAX_MINUTES_WAITING_TO_PAY;

export {
    MAX_MINUTES_WAITING_TO_PAY,
    MAX_DAYS_WAITING_FOR_SHOP_CONFIRMATION,
    ORDER_MOMO_TRANSACTION_EXPIRY_TIME_IN_MINUTE,
};
