const PAYMENT_WITH_CASH = 1;
const PAYMENT_WITH_MOMO = 2;
const PAYMENT_WITH_ATM = 3;
const PAYMENT_WITH_CREDIT_CARD = 4;

export { PAYMENT_WITH_CASH, PAYMENT_WITH_MOMO, PAYMENT_WITH_ATM, PAYMENT_WITH_CREDIT_CARD };
